name: build apk test

on:
  push:
    branches:
      - master
jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.0
      - name: Install Node Packages & add cap/android
        run: npm i && npx cap add android
      - name: Build App
        run: npm run build:app && npm run cap-sync:android
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build the APK
        run: cd android && bash gradlew assembleDebug --stacktrace
      - name: Upload to FileIO
        run: curl -F file=@android/app/build/outputs/apk/debug/app-debug.apk file.io
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
  
  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} 
